spring:
  application:
    name: indetity

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopflow_identity}
    username: ${DB_USERNAME:shopflow_admin}
    password: ${DB_PASSWORD:shopflow_admin_password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopflow_identity}
    user: ${DB_USERNAME:shopflow_admin}
    password: ${DB_PASSWORD:shopflow_admin_password}
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

server:
  port: 8080